---
inherits:
  - full_pep8
  - strictness_veryhigh

pylint:
  disable:
    - cyclic-import
    - C0330
    - C0326
    - wrong-import-order

pep8:
  disable:
    - E203
    - W503
test-warnings: true
